package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestMetadataDemo'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestMetadataDemo")) {
    check(artifactRules == "build/reports/tests/test => gradle_test_report.zip") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        build/reports/tests/test => gradle_test_report.zip
        pictureForAttention.png
    """.trimIndent()
}
