package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestMetadataDemo'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestMetadataDemo")) {
    params {
        add {
            param("teamcity.build.serviceMessages.logOriginal", "true")
        }
    }
}
